language: node_js
node_js:
  - "8"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -e 'create table if not exists test.tbl1(id int auto_increment primary key, name varchar(200), value varchar(200));'
script:
  # - "npm test"
  - "npm run build"
  # - "npm run test-nyc"
# after_script:
  # - "npm run test-nyc"
  # - "npm run build"

cache:
  directories:
  - node_modules



deploy:
  - provider: npm
    skip_cleanup: true
    email: heifade@126.com
    api_key: $NPM_TOKEN
    on:
      branch: master
      repo: heifade/server-i
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs
    on:
      branch: master

