language: node_js
node_js:
  - "8"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -e 'create table if not exists tbl1(id int AUTO_INCREMENT, name varchar(200), value varchar(200));'
script :
  - "npm run start"
  - "npm test"
  # - "npm run build"
  # - "git add es docs"
  # - "git commit -m 'rebuild by travis'"
  # - "git push origin master"
after_script:
  - "npm run test-nyc"

cache:
  directories:
  - node_modules

# deploy:
#   provider: npm
#   email: heifade@126.com
#   api_key: $NPM_TOKEN
#   on:
#     tags: true
#     repo: heifade/mysql-i

